apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  labels:
    app.kubernetes.io/component: deliverable
    app.kubernetes.io/part-of: tanzu-java-web-app-orig
    app.tanzu.vmware.com/deliverable-type: web
    app.tanzu.vmware.com/has-tests: "true"
  name: tanzu-java-web-app-orig
  namespace: canary-app
spec:
  params:
  - name: gitops_ssh_secret
    value: git-ssh
  source:
    git:
      ref:
        branch: test
      url: ssh://git@github.com/mgbrodi/devops-tanzu-java-web-app-orig
